services:                                                                                                  
    api:                                                                                                     
      build: .                                                                                               
      ports:                                                                                                 
        - "127.0.0.1:8081:8000"                                                                              
      env_file:                                                                                              
        - .env                                                                                               
      depends_on:                                                                                            
        db:                                                                                                  
          condition: service_healthy                                                                         
        redis:                                                                                               
          condition: service_healthy                                                                         
      volumes:                                                                                               
        - ./backend:/app                                                                                     
        - ./alembic:/app/alembic                                                                             
        - ./alembic.ini:/app/alembic.ini                                                                     
      restart: unless-stopped                                                                                
      container_name: mail_service_api                                                                       
                                                                                                             
    db:                                                                                                      
      image: mysql:8.0                                                                                       
      ports:                                                                                                 
        - "127.0.0.1:3307:3306"                                                                              
      environment:                                                                                           
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}                                            
        MYSQL_DATABASE: ${MYSQL_DATABASE:-mail_service}                                                      
        MYSQL_USER: ${MYSQL_USER:-mailuser}                                                                  
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mailpassword}                                                      
      volumes:                                                                                               
        - mail_service_mysql:/var/lib/mysql                                                                  
      command: >                                                                                             
        --character-set-server=utf8mb4                                                                       
        --collation-server=utf8mb4_unicode_ci                                                                
        --default-authentication-plugin=mysql_native_password                                                
      healthcheck:                                                                                           
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root",                                 
  "-p${MYSQL_ROOT_PASSWORD:-rootpassword}"]                                                                  
        interval: 10s                                                                                        
        timeout: 5s                                                                                          
        retries: 5                                                                                           
      restart: unless-stopped                                                                                
      container_name: mail_service_db                                                                        
                                                                                                             
    redis:                                                                                                   
      image: redis:7-alpine                                                                                  
      ports:                                                                                                 
        - "127.0.0.1:6380:6379"                                                                              
      volumes:                                                                                               
        - mail_service_redis:/data                                                                           
      healthcheck:                                                                                           
        test: ["CMD", "redis-cli", "ping"]                                                                   
        interval: 10s                                                                                        
        timeout: 5s                                                                                          
        retries: 5                                                                                           
      restart: unless-stopped                                                                                
      container_name: mail_service_redis                                                                     
                                                                                                             
    worker:                                                                                                  
      build: .                                                                                               
      command: python -m app.worker                                                                          
      env_file:                                                                                              
        - .env                                                                                               
      depends_on:                                                                                            
        db:                                                                                                  
          condition: service_healthy                                                                         
        redis:                                                                                               
          condition: service_healthy                                                                         
      volumes:                                                                                               
        - ./backend:/app                                                                                     
      restart: unless-stopped                                                                                
      container_name: mail_service_worker                                                                    
                                                                                                             
    scheduler:                                                                                               
      build: .                                                                                               
      command: python -m app.scheduler                                                                       
      env_file:                                                                                              
        - .env                                                                                               
      depends_on:                                                                                            
        db:                                                                                                  
          condition: service_healthy                                                                         
        redis:                                                                                               
          condition: service_healthy                                                                         
      volumes:                                                                                               
        - ./backend:/app                                                                                     
      restart: unless-stopped                                                                                
      container_name: mail_service_scheduler                                                                 
                                                                                                             
  volumes:                                                                                                   
    mail_service_mysql:                                                                                      
    mail_service_redis:   
