"""create_all_tables

Revision ID: ba5a7bc54121
Revises: 
Create Date: 2026-02-02 11:39:10.930465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5a7bc54121'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='プラン名'),
    sa.Column('description', sa.Text(), nullable=True, comment='プラン説明'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stripe_product_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False, comment='月額料金 (円)'),
    sa.Column('schedule_type', sa.Enum('daily', 'weekday', 'sheets', name='schedule_type'), nullable=False, comment='配信タイプ: daily=毎日, weekday=曜日指定, sheets=Sheets日付'),
    sa.Column('schedule_weekdays', sa.JSON(), nullable=True, comment='曜日指定 (0=月〜6=日)'),
    sa.Column('send_time', sa.Time(), nullable=False, comment='配信時刻 (JST)'),
    sa.Column('sheets_url', sa.String(length=500), nullable=True, comment='Google Sheets URL'),
    sa.Column('model', sa.String(length=50), nullable=False, comment='OpenAIモデル名'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='システムプロンプト'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='ユーザープロンプト (変数含む)'),
    sa.Column('batch_send_enabled', sa.Boolean(), nullable=False, comment='まとめて送信'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_price_id'),
    sa.UniqueConstraint('stripe_product_id')
    )
    op.create_table('promotion_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='プロモーションコード'),
    sa.Column('stripe_promotion_code_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_coupon_id', sa.String(length=255), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False, comment='percent_off / amount_off'),
    sa.Column('discount_value', sa.Integer(), nullable=False, comment='割引値 (% or 円)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_redemptions', sa.Integer(), nullable=True, comment='最大使用回数'),
    sa.Column('times_redeemed', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='有効期限'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('stripe_promotion_code_id')
    )
    op.create_table('report_deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False, comment='レポート対象日'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0=未送信, 1=送信中, 2=送信完了, 3=送信失敗'),
    sa.Column('total_admins', sa.Integer(), nullable=False, comment='送信対象管理者数'),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date')
    )
    op.create_table('service_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('site_url', sa.String(length=500), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('openai_api_key_enc', sa.Text(), nullable=True, comment='OpenAI APIキー (暗号化)'),
    sa.Column('resend_api_key_enc', sa.Text(), nullable=True, comment='Resend APIキー (暗号化)'),
    sa.Column('stripe_secret_key_enc', sa.Text(), nullable=True, comment='Stripe Secret Key (暗号化)'),
    sa.Column('stripe_publishable_key', sa.String(length=255), nullable=True, comment='Stripe Publishable Key (公開)'),
    sa.Column('stripe_webhook_secret_enc', sa.Text(), nullable=True, comment='Stripe Webhook Secret (暗号化)'),
    sa.Column('resend_webhook_secret_enc', sa.Text(), nullable=True, comment='Resend Webhook Secret (暗号化)'),
    sa.Column('resend_webhook_enabled', sa.Boolean(), nullable=False, comment='Resend Webhook有効化'),
    sa.Column('allow_multiple_plans', sa.Boolean(), nullable=False, comment='複数プラン同時加入許可'),
    sa.Column('terms_md', sa.Text(), nullable=True, comment='利用規約'),
    sa.Column('company_md', sa.Text(), nullable=True, comment='運営会社情報'),
    sa.Column('cancel_md', sa.Text(), nullable=True, comment='解約ポリシー'),
    sa.Column('tokusho_md', sa.Text(), nullable=True, comment='特定商取引法に基づく表記'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_no', sa.String(length=8), nullable=False, comment='会員番号 (10000001〜)'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name_last', sa.String(length=100), nullable=False, comment='姓'),
    sa.Column('name_first', sa.String(length=100), nullable=False, comment='名'),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('trial_used', sa.Boolean(), nullable=False, comment='トライアル使用済み'),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=True, comment='配信停止トークン'),
    sa.Column('deliverable', sa.Boolean(), nullable=False, comment='配信可能 (bounce/complaintでfalse)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_member_no'), 'users', ['member_no'], unique=True)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('send_type', sa.Enum('scheduled', 'manual', 'system', name='send_type'), nullable=False, comment='送信タイプ'),
    sa.Column('status', sa.Enum('running', 'success', 'partial_failed', 'failed', 'stopped', name='delivery_status'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True, comment='メール件名'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='総送信数'),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_plan_id'), 'deliveries', ['plan_id'], unique=False)
    op.create_table('plan_external_data_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('external_data_path', sa.String(length=500), nullable=False, comment='Firestoreパス (collection/doc/~)'),
    sa.Column('firebase_key_json_enc', sa.Text(), nullable=True, comment='Firebase Service Account JSON (暗号化)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_table('plan_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('var_name', sa.String(length=100), nullable=False, comment='変数名 (プロンプト内{var_name}に対応)'),
    sa.Column('label', sa.String(length=255), nullable=False, comment='質問ラベル'),
    sa.Column('question_type', sa.Enum('text', 'textarea', 'number', 'date', 'select', 'radio', 'checkbox', 'array', name='question_type'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True, comment='選択肢 (select/radio/checkbox用)'),
    sa.Column('array_max', sa.Integer(), nullable=True, comment='array型の最大件数'),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='表示順'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_questions_plan_id'), 'plan_questions', ['plan_id'], unique=False)
    op.create_table('plan_summary_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('summary_prompt', sa.Text(), nullable=False, comment='あらすじ生成プロンプト'),
    sa.Column('summary_length_target', sa.Integer(), nullable=False, comment='あらすじ目標文字数'),
    sa.Column('summary_max_keep', sa.Integer(), nullable=False, comment='保持するあらすじ最大件数'),
    sa.Column('summary_inject_count', sa.Integer(), nullable=False, comment='GPT生成時に注入するあらすじ件数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_table('report_delivery_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_delivery_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0=未送信, 1=送信中, 2=送信完了, 3=送信失敗'),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_delivery_id'], ['report_deliveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_delivery_items_admin_user_id'), 'report_delivery_items', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_report_delivery_items_report_delivery_id'), 'report_delivery_items', ['report_delivery_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('member_no_snapshot', sa.String(length=8), nullable=False, comment='会員番号スナップショット'),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'canceled', 'unpaid', 'incomplete', name='subscription_status'), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('user_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False, comment='あらすじテキスト'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_summaries_plan_id'), 'user_summaries', ['plan_id'], unique=False)
    op.create_index(op.f('ix_user_summaries_user_id'), 'user_summaries', ['user_id'], unique=False)
    op.create_table('delivery_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('member_no_snapshot', sa.String(length=8), nullable=False, comment='会員番号スナップショット'),
    sa.Column('document_key', sa.String(length=255), nullable=True, comment='外部データドキュメントキー'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0=未実行, 1=実行中, 2=完了, 3=エラー'),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('resend_message_id', sa.String(length=255), nullable=True, comment='Resend メッセージID'),
    sa.Column('last_error_code', sa.String(length=50), nullable=True, comment='最終エラーコード'),
    sa.Column('last_error_message', sa.Text(), nullable=True, comment='最終エラーメッセージ'),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_items_delivery_id'), 'delivery_items', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_delivery_items_user_id'), 'delivery_items', ['user_id'], unique=False)
    op.create_table('progress_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='配信日 (JST)'),
    sa.Column('send_type', sa.Enum('scheduled', 'manual', name='progress_send_type'), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0=未実行, 1=実行中, 2=完了, 3=エラー'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'date', 'send_type', 'delivery_id', name='uq_plan_date_type_delivery')
    )
    op.create_index(op.f('ix_progress_plan_plan_id'), 'progress_plan', ['plan_id'], unique=False)
    op.create_table('progress_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('document_key', sa.String(length=255), nullable=True, comment='外部データドキュメントキー'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='0=未実行, 1=実行中, 2=完了, 3=エラー'),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id', 'user_id', 'document_key', name='uq_delivery_user_doc')
    )
    op.create_index(op.f('ix_progress_tasks_delivery_id'), 'progress_tasks', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_progress_tasks_user_id'), 'progress_tasks', ['user_id'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False, comment='INFO/WARNING/ERROR/CRITICAL'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='イベント種別'),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('member_no_snapshot', sa.String(length=8), nullable=True, comment='会員番号スナップショット'),
    sa.Column('delivery_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True, comment='詳細データ'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_delivery_id'), 'system_logs', ['delivery_id'], unique=False)
    op.create_index(op.f('ix_system_logs_event_type'), 'system_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_plan_id'), 'system_logs', ['plan_id'], unique=False)
    op.create_index(op.f('ix_system_logs_user_id'), 'system_logs', ['user_id'], unique=False)
    op.create_table('user_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_value', sa.Text(), nullable=True, comment='回答値 (JSON文字列の場合あり)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['plan_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question')
    )
    op.create_index(op.f('ix_user_answers_question_id'), 'user_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_user_answers_user_id'), 'user_answers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_answers_user_id'), table_name='user_answers')
    op.drop_index(op.f('ix_user_answers_question_id'), table_name='user_answers')
    op.drop_table('user_answers')
    op.drop_index(op.f('ix_system_logs_user_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_plan_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_event_type'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_delivery_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_progress_tasks_user_id'), table_name='progress_tasks')
    op.drop_index(op.f('ix_progress_tasks_delivery_id'), table_name='progress_tasks')
    op.drop_table('progress_tasks')
    op.drop_index(op.f('ix_progress_plan_plan_id'), table_name='progress_plan')
    op.drop_table('progress_plan')
    op.drop_index(op.f('ix_delivery_items_user_id'), table_name='delivery_items')
    op.drop_index(op.f('ix_delivery_items_delivery_id'), table_name='delivery_items')
    op.drop_table('delivery_items')
    op.drop_index(op.f('ix_user_summaries_user_id'), table_name='user_summaries')
    op.drop_index(op.f('ix_user_summaries_plan_id'), table_name='user_summaries')
    op.drop_table('user_summaries')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_report_delivery_items_report_delivery_id'), table_name='report_delivery_items')
    op.drop_index(op.f('ix_report_delivery_items_admin_user_id'), table_name='report_delivery_items')
    op.drop_table('report_delivery_items')
    op.drop_table('plan_summary_settings')
    op.drop_index(op.f('ix_plan_questions_plan_id'), table_name='plan_questions')
    op.drop_table('plan_questions')
    op.drop_table('plan_external_data_settings')
    op.drop_index(op.f('ix_deliveries_plan_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_users_member_no'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('service_settings')
    op.drop_table('report_deliveries')
    op.drop_table('promotion_codes')
    op.drop_table('plans')
    # ### end Alembic commands ###
